language: node_js

node_js:
  - "10"

cache:
  yarn: true

install:
  - yarn
  - cd functions && npm install && cd ..

script:
  - npm test
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then npm run deploy:ci; fi'
