import type { NextPage } from "next";
import Head from "next/head";

import Board from "../components/Board";
import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Header tab="board"></Header>

      <main>
        <Board></Board>
      </main>
    </>
  );
};

export default Home;
